# Generated by Django 3.1.2 on 2020-10-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
