# Generated by Django 3.1.2 on 2020-11-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuser', '0002_auto_20201011_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_adm',
            field=models.BooleanField(default=False),
        ),
    ]
