# Generated by Django 3.1.2 on 2020-10-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20201009_1751'),
        ('pis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer_course',
            options={'managed': True, 'verbose_name': 'Lecturer_Course', 'verbose_name_plural': 'Lecturer_Courses'},
        ),
        migrations.AlterModelOptions(
            name='student_attendence',
            options={'managed': True, 'verbose_name': 'Student_Attendence', 'verbose_name_plural': 'Student_Attendences'},
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='semester',
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.semester'),
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='subject',
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.subject'),
        ),
    ]
