# Generated by Django 3.1.2 on 2020-10-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0031_auto_20201017_1516'),
        ('pis', '0002_auto_20201009_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_load',
            name='Education_level',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10),
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_course_lecturer', to='sis.course'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_of_lecturer', to='sis.department'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_of_lecturer', to='sis.program'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pis.lecturer'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='work_status',
            field=models.CharField(blank=True, choices=[('part time', 'Part Time'), ('full time', 'Full Time')], max_length=10, null=True),
        ),
    ]
