# Generated by Django 3.1.2 on 2020-10-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0003_auto_20201018_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_load',
            old_name='Education_level',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='work_load',
            old_name='Lecturer_course',
            new_name='lecturer_course',
        ),
        migrations.RenameField(
            model_name='work_load',
            old_name='Lecturer_dept',
            new_name='lecturer_dept',
        ),
        migrations.RenameField(
            model_name='work_load',
            old_name='Lecturer_program',
            new_name='lecturer_program',
        ),
        migrations.RenameField(
            model_name='work_load',
            old_name='Lecturer_subject',
            new_name='lecturer_subject',
        ),
    ]
