# Generated by Django 3.1.2 on 2020-10-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0031_auto_20201017_1516'),
        ('pis', '0004_auto_20201018_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_load',
            name='lecturer_course',
        ),
        migrations.RemoveField(
            model_name='work_load',
            name='lecturer_subject',
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_course',
            field=models.ManyToManyField(blank=True, related_name='list_course_lecturer', to='sis.Course'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='Lecturer_subject',
            field=models.ManyToManyField(blank=True, related_name='list_subject_lecturer', to='sis.Subject'),
        ),
    ]
