# Generated by Django 3.1.2 on 2020-10-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0031_auto_20201017_1516'),
        ('pis', '0006_auto_20201018_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_load',
            name='Lecturer_subject',
        ),
        migrations.AddField(
            model_name='work_load',
            name='date1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='date3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='date4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='date5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer1', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer2', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer3', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer4', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer5', to='sis.subject'),
        ),
        migrations.AddField(
            model_name='work_load',
            name='subject6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_subject_lecturer6', to='sis.subject'),
        ),
    ]
