# Generated by Django 3.1.2 on 2020-10-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0007_auto_20201018_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Lecturer_Course',
        ),
    ]
