# Generated by Django 3.1.2 on 2020-10-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0036_semester_course'),
        ('pis', '0010_auto_20201019_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_course',
            name='sutdent',
        ),
        migrations.AlterField(
            model_name='my_course',
            name='semester',
            field=models.ManyToManyField(related_name='my_course_semester', to='sis.Semester'),
        ),
        migrations.AlterField(
            model_name='my_course',
            name='subject',
            field=models.ManyToManyField(related_name='my_course_subject', to='sis.Subject'),
        ),
    ]
