# Generated by Django 3.1.2 on 2020-10-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0037_auto_20201019_1344'),
        ('pis', '0011_auto_20201019_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_course',
            name='course',
            field=models.ManyToManyField(related_name='my_course_course', to='sis.Course'),
        ),
        migrations.AddField(
            model_name='my_course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_course_lecturer', to='pis.lecturer'),
        ),
    ]
