# Generated by Django 3.1.2 on 2020-10-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0012_auto_20201019_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_course',
            options={'managed': True, 'verbose_name': 'My_Course', 'verbose_name_plural': 'My_Courses'},
        ),
        migrations.RemoveField(
            model_name='my_course',
            name='subject',
        ),
    ]
