# Generated by Django 3.1.2 on 2020-10-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0040_auto_20201020_1256'),
        ('pis', '0014_auto_20201020_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_course',
            name='course',
        ),
        migrations.AddField(
            model_name='my_course',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_course_course', to='sis.course'),
        ),
        migrations.RemoveField(
            model_name='my_course',
            name='semester',
        ),
        migrations.AddField(
            model_name='my_course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_course_semester', to='sis.semester'),
        ),
    ]
