# Generated by Django 3.1.2 on 2020-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0015_auto_20201020_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_course',
            name='name',
            field=models.CharField(default='rafi', max_length=20),
            preserve_default=False,
        ),
    ]
