# Generated by Django 3.1.2 on 2020-10-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0040_auto_20201020_1256'),
        ('pis', '0016_my_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='num_of_day',
            new_name='absent',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='num_of_days',
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pis.lecturer'),
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='present',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.semester'),
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.subject'),
        ),
    ]
