# Generated by Django 3.1.2 on 2020-10-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0018_auto_20201021_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject_Attendence',
        ),
    ]
