# Generated by Django 3.1.2 on 2020-10-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0020_auto_20201021_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_attendence',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='subject_attendence',
            name='present',
        ),
        migrations.AlterField(
            model_name='student_attendence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance', to='pis.subject_attendence'),
        ),
    ]
