# Generated by Django 3.1.2 on 2020-10-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0025_auto_20201022_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance_report',
        ),
    ]
