# Generated by Django 3.1.2 on 2020-10-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0027_auto_20201022_2144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_attendence',
            managers=[
            ],
        ),
    ]
