# Generated by Django 3.1.2 on 2020-10-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0028_auto_20201022_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_attendence',
            name='date',
        ),
        migrations.AddField(
            model_name='subject_attendence',
            name='hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Attendance_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('attend', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance_report', to='pis.student_attendence')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_reprot', to='pis.subject_attendence')),
            ],
        ),
    ]
