# Generated by Django 3.1.2 on 2020-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0029_auto_20201022_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendence',
            name='absent_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_attendence',
            name='preset_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
