# Generated by Django 3.1.2 on 2020-10-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0031_remove_student_attendence_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='preset_days',
            new_name='prsent_days',
        ),
    ]
