# Generated by Django 3.1.2 on 2020-10-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0032_auto_20201023_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='prsent_days',
            new_name='present_days',
        ),
    ]
