# Generated by Django 3.1.2 on 2020-10-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0033_auto_20201023_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Files_of_lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('files', models.FileField(blank=True, upload_to='rules/rule/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_of_lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('handbook', models.ManyToManyField(blank=True, related_name='handbook_file', to='pis.Notice_Files_of_lecturer')),
                ('policy', models.ManyToManyField(blank=True, related_name='policies_file', to='pis.Notice_Files_of_lecturer')),
                ('records_forms', models.ManyToManyField(blank=True, related_name='records_file', to='pis.Notice_Files_of_lecturer')),
                ('rule', models.ManyToManyField(blank=True, related_name='rules_file', to='pis.Notice_Files_of_lecturer')),
            ],
            options={
                'verbose_name': 'Notice_of_lecturer',
                'verbose_name_plural': 'Notice_of_lecturers',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
