# Generated by Django 3.1.2 on 2020-10-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0034_notice_files_of_lecturer_notice_of_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_of_lecturer',
            name='handbook',
        ),
        migrations.AddField(
            model_name='notice_of_lecturer',
            name='handbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.RemoveField(
            model_name='notice_of_lecturer',
            name='policy',
        ),
        migrations.AddField(
            model_name='notice_of_lecturer',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.RemoveField(
            model_name='notice_of_lecturer',
            name='records_forms',
        ),
        migrations.AddField(
            model_name='notice_of_lecturer',
            name='records_forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.RemoveField(
            model_name='notice_of_lecturer',
            name='rule',
        ),
        migrations.AddField(
            model_name='notice_of_lecturer',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_file', to='pis.notice_files_of_lecturer'),
        ),
    ]
