# Generated by Django 3.1.2 on 2020-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0035_auto_20201026_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_of_lecturer',
            name='handbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.AlterField(
            model_name='notice_of_lecturer',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.AlterField(
            model_name='notice_of_lecturer',
            name='records_forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_file', to='pis.notice_files_of_lecturer'),
        ),
        migrations.AlterField(
            model_name='notice_of_lecturer',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_file', to='pis.notice_files_of_lecturer'),
        ),
    ]
