# Generated by Django 3.1.2 on 2020-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201028_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control_student_payment',
            options={},
        ),
        migrations.AddField(
            model_name='control_student_payment',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='control_student_payment',
            table=None,
        ),
    ]
