# Generated by Django 3.1.2 on 2020-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Subjects',
                'verbose_name_plural': 'Subjectss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
