# Generated by Django 3.1.2 on 2020-10-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
