# Generated by Django 3.1.2 on 2020-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20201009_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tution',
            field=models.PositiveIntegerField(default=5000),
            preserve_default=False,
        ),
    ]
