# Generated by Django 3.1.2 on 2020-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0006_department_tution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
