# Generated by Django 3.1.2 on 2020-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20201012_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
