# Generated by Django 3.1.2 on 2020-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_auto_20201012_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to='department/images/'),
        ),
    ]
