# Generated by Django 3.1.2 on 2020-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0010_department_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='enrolled',
            field=models.PositiveIntegerField(blank=True, default=250),
            preserve_default=False,
        ),
    ]
