# Generated by Django 3.1.2 on 2020-10-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_department_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='enrolled',
        ),
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='text',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tution',
        ),
    ]
