# Generated by Django 3.1.2 on 2020-10-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0013_auto_20201013_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.course'),
        ),
    ]
