# Generated by Django 3.1.2 on 2020-10-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0014_auto_20201013_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True, 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='course',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=150)),
                ('course', models.ManyToManyField(blank=True, null=True, to='sis.Course')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.program'),
        ),
    ]
