# Generated by Django 3.1.2 on 2020-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0018_course_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='about',
            new_name='faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='department',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.IntegerField(blank=True, default=2020, help_text='give a year'),
            preserve_default=False,
        ),
    ]
