# Generated by Django 3.1.2 on 2020-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0019_auto_20201013_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject_list', to='sis.Subject'),
        ),
    ]
