# Generated by Django 3.1.2 on 2020-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0020_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
