# Generated by Django 3.1.2 on 2020-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0021_auto_20201013_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
