# Generated by Django 3.1.2 on 2020-10-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0027_auto_20201015_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstructure',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_status', to='sis.course'),
        ),
    ]
