# Generated by Django 3.1.2 on 2020-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0028_programstructure_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current',
            field=models.ManyToManyField(blank=True, related_name='curent_subject_status', to='sis.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='faield',
            field=models.ManyToManyField(blank=True, related_name='failed_subject_status', to='sis.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='nerver',
            field=models.ManyToManyField(blank=True, related_name='never_subject_status', to='sis.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='passed',
            field=models.ManyToManyField(blank=True, related_name='passed_subject_status', to='sis.Subject'),
        ),
        migrations.DeleteModel(
            name='ProgramStructure',
        ),
    ]
