# Generated by Django 3.1.2 on 2020-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0029_auto_20201016_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='handbook',
            field=models.FileField(blank=True, upload_to='rules/handbook/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='important',
            field=models.FileField(blank=True, upload_to='rules/important/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='policy',
            field=models.FileField(blank=True, upload_to='rules/policies/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='rule',
            field=models.FileField(blank=True, upload_to='rules/rule/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20),
        ),
    ]
