# Generated by Django 3.1.2 on 2020-10-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0031_auto_20201017_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='currentstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='user',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='program',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
    ]
