# Generated by Django 3.1.2 on 2020-10-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0036_semester_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
