# Generated by Django 3.1.2 on 2020-10-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0037_auto_20201019_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='currentstatus',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='student',
            new_name='user',
        ),
    ]
