# Generated by Django 3.1.2 on 2020-10-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0038_auto_20201019_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='currentstatus',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='student',
        ),
    ]
