# Generated by Django 3.1.2 on 2020-10-25 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0041_student_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
