# Generated by Django 3.1.2 on 2020-10-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0042_student_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True, 'ordering': ['-join'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
