# Generated by Django 3.1.2 on 2020-11-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0045_auto_20201101_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
    ]
