# Generated by Django 3.1.2 on 2020-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0046_remove_student_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('about', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Facultys',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
