# Generated by Django 3.1.2 on 2020-11-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0047_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='about',
        ),
    ]
