# Generated by Django 3.1.2 on 2020-11-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0050_auto_20201105_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_student', to='sis.student'),
        ),
    ]
