# Generated by Django 3.1.2 on 2020-11-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0051_auto_20201105_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_7th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_6th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_5th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_4th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_3rd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_2nd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_1st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('credit', models.IntegerField()),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.program')),
            ],
        ),
    ]
