# Generated by Django 3.1.2 on 2020-11-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0052_courses_semester_1st_semester_2nd_semester_3rd_semester_4th_semester_5th_semester_6th_semester_7th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1st',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_2nd',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_3rd',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_4th',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_5th',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_6th',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
        migrations.AlterField(
            model_name='semester_7th',
            name='course',
            field=models.ManyToManyField(to='sis.Courses'),
        ),
    ]
