# Generated by Django 3.1.2 on 2020-11-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0055_auto_20201106_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ManyToManyField(related_name='semester_course', to='sis.Courses'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_program', to='sis.program'),
        ),
    ]
