# Generated by Django 3.1.2 on 2020-11-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0058_auto_20201107_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='student_courses', to='sis.Courses'),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_department', to='sis.department'),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_faculty', to='sis.faculty'),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_program', to='sis.program'),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
