# Generated by Django 3.1.2 on 2020-11-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0060_auto_20201107_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstatus',
            name='course',
        ),
    ]
