# Generated by Django 3.1.2 on 2020-11-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0061_remove_currentstatus_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Attendance',
        ),
        migrations.DeleteModel(
            name='Result_Of_Dept',
        ),
        migrations.DeleteModel(
            name='Result_Of_Semester',
        ),
    ]
