# Generated by Django 3.1.2 on 2020-11-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0063_auto_20201108_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course_name',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.department'),
        ),
        migrations.AddField(
            model_name='student_course_name',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.faculty'),
        ),
    ]
