# Generated by Django 3.1.2 on 2020-11-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0064_auto_20201108_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Reg_Course',
            new_name='Reg_Course_Program1',
        ),
    ]
