# Generated by Django 3.1.2 on 2020-11-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0069_auto_20201109_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='q',
        ),
        migrations.DeleteModel(
            name='Course_Registration',
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
