# Generated by Django 3.1.2 on 2020-11-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0036_auto_20201027_0221'),
        ('sis', '0072_remove_registration_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstatus',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='currentstatus',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='currentstatus',
            name='program',
        ),
        migrations.RemoveField(
            model_name='currentstatus',
            name='semester',
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pis.lecturer'),
        ),
    ]
