# Generated by Django 3.1.2 on 2020-11-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0036_auto_20201027_0221'),
        ('sis', '0073_auto_20201129_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatus',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentstatus', to='pis.lecturer'),
        ),
    ]
