# Generated by Django 3.1.2 on 2020-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0075_auto_20201129_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_No',
            field=models.CharField(blank=True, default='62988353526', max_length=11, null=True, unique=True),
        ),
    ]
