# Generated by Django 3.1.2 on 2020-11-03 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0047_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adm_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(upload_to='adm/images/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('fathter_name', models.CharField(max_length=50)),
                ('father_phone', models.CharField(max_length=11)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_phone', models.CharField(max_length=11)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_department', to='sis.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_faculty', to='sis.faculty')),
            ],
        ),
    ]
