# Generated by Django 3.1.2 on 2020-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_form',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
