# Generated by Django 3.1.2 on 2020-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0047_faculty'),
        ('adm', '0002_auto_20201103_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adm_Form',
            new_name='Admission',
        ),
    ]
