# Generated by Django 3.1.2 on 2020-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20201103_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='7711824008', editable=False, max_length=10, null=True),
        ),
    ]
