# Generated by Django 3.1.2 on 2020-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20201103_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='7847980449', max_length=10, null=True, unique=True),
        ),
    ]
