# Generated by Django 3.1.2 on 2020-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20201103_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='5467579191', max_length=11, null=True, unique=True),
        ),
    ]
