# Generated by Django 3.1.2 on 2020-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_auto_20201103_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='92363041548', max_length=11, null=True, unique=True),
        ),
    ]
