# Generated by Django 3.1.2 on 2020-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_auto_20201105_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='97271262482', max_length=11, null=True, unique=True),
        ),
    ]
