# Generated by Django 3.1.2 on 2020-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_auto_20201105_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='49378286436', max_length=11, null=True, unique=True),
        ),
    ]
