# Generated by Django 3.1.2 on 2020-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_auto_20201105_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='97678499885', max_length=11, null=True, unique=True),
        ),
    ]
