# Generated by Django 3.1.2 on 2020-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_auto_20201105_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='10861528639', max_length=11, null=True, unique=True),
        ),
    ]
