# Generated by Django 3.1.2 on 2020-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_auto_20201105_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='56266609545', max_length=11, null=True, unique=True),
        ),
    ]
