# Generated by Django 3.1.2 on 2020-11-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0016_auto_20201105_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='22144859683', max_length=11, null=True, unique=True),
        ),
    ]
