# Generated by Django 3.1.2 on 2020-11-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_auto_20201106_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='12484668674', max_length=11, null=True, unique=True),
        ),
    ]
