# Generated by Django 3.1.2 on 2020-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_auto_20201106_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='19615744596', max_length=11, null=True, unique=True),
        ),
    ]
