# Generated by Django 3.1.2 on 2020-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0021_auto_20201107_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='19728981265', max_length=11, null=True, unique=True),
        ),
    ]
