# Generated by Django 3.1.2 on 2020-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0022_auto_20201107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='70603043807', max_length=11, null=True, unique=True),
        ),
    ]
