# Generated by Django 3.1.2 on 2020-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0024_auto_20201107_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='67211054692', max_length=11, null=True, unique=True),
        ),
    ]
