# Generated by Django 3.1.2 on 2020-11-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0025_auto_20201107_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='70841713565', max_length=11, null=True, unique=True),
        ),
    ]
