# Generated by Django 3.1.2 on 2020-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0030_auto_20201108_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='26801636280', max_length=11, null=True, unique=True),
        ),
    ]
