# Generated by Django 3.1.2 on 2020-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0033_auto_20201109_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='93507070440', max_length=11, null=True, unique=True),
        ),
    ]
