# Generated by Django 3.1.2 on 2020-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0034_auto_20201109_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='18248893562', max_length=11, null=True, unique=True),
        ),
    ]
