# Generated by Django 3.1.2 on 2020-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0036_auto_20201112_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='59629231038', max_length=11, null=True, unique=True),
        ),
    ]
