# Generated by Django 3.1.2 on 2020-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0038_auto_20201127_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='78671370407', max_length=11, null=True, unique=True),
        ),
    ]
