# Generated by Django 3.1.2 on 2020-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0040_auto_20201129_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_No',
            field=models.CharField(blank=True, default='37840560062', max_length=11, null=True, unique=True),
        ),
    ]
